#restraint_index atom_index1 res1 atom_name1 atom_index2 res2 atom_name2 atom_index3 res3 atom_name3 atom_index4 res4 atom_name4 exp_J_coupling(Hz) model_J_coupling(Hz)
0            45       UNK1     H25          3        UNK1     C2           4        UNK1     C3           44       UNK1     H24           15.5000      11.5936
1            21       UNK1     H5           20       UNK1     C14          19       UNK1     C13          22       UNK1     H6            16.1000      11.5880
1            22       UNK1     H6           19       UNK1     C13          13       UNK1     C11          23       UNK1     H7             6.1000      11.5994
1            28       UNK1     H11          11       UNK1     C9           10       UNK1     C8           29       UNK1     H12            6.3000      10.8603
