{% set version = "2.0b0" %}

package:
  name: biceps
  version: {{ version }}

source:
  git_url: https://github.com/vvoelz/biceps.git

install:
    - conda config --add channels conda-forge
    - conda config --set channel_priority strict

channels:
    - conda-forge

build:
  number: 0

requirements:
  host:
    - python<3.8
    - pip
  run:
    - python<3.8
    - numpy>=1.7.0
    - mdtraj
    - pymbar
    - matplotlib

test:
  imports:
    - biceps

about:
  home: https://github.com/vvoelz/biceps
  license: MIT
  #summary: ''
  description: |
      BICePs - Bayesian Inference of Conformational Populations
      The BICePs algorithm (Bayesian Inference of Conformational Populations) is a statistically rigorous Bayesian inference method to reconcile theoretical predictions of conformational state populations with sparse and/or noisy experimental measurements and objectively compare different models.
  dev_url: https://github.com/vvoelz/biceps
  doc_url: https://biceps.readthedocs.io/en/latest/index.html
  doc_source_url: https://biceps.readthedocs.io/en/latest/index.html


