/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE__PosteriorSampler
#define __PYX_HAVE__PosteriorSampler

#include "Python.h"

#ifndef __PYX_HAVE_API__PosteriorSampler

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C std::vector<std::vector<double> >  get_fwd_model_weights(PyObject *);
__PYX_EXTERN_C std::vector<double>  compute_prior_populations(PyObject *);
__PYX_EXTERN_C std::vector<std::vector<float> >  compile_nuisance_parameters(PyObject *);
__PYX_EXTERN_C std::vector<std::vector<std::vector<double> > >  get_restraint_attr(PyObject *, std::string);
__PYX_EXTERN_C std::vector<std::vector<std::vector<double> > >  get_phi_angles(PyObject *);
__PYX_EXTERN_C std::vector<double>  get_phase_shifts(PyObject *);
__PYX_EXTERN_C std::vector<int>  get_fmo_restraint_indices(PyObject *);
__PYX_EXTERN_C std::vector<std::vector<double> >  get_fwd_model_parameters(PyObject *, int);
__PYX_EXTERN_C std::vector<double>  get_prior_model_parameter_attr(PyObject *, std::string);
__PYX_EXTERN_C std::vector<std::string>  get_pmp_prior_models(PyObject *);
__PYX_EXTERN_C std::vector<std::vector<double> >  get_fwd_model_parameter_attr(PyObject *, std::string);
__PYX_EXTERN_C std::vector<std::vector<double> >  get_min_max_fwd_model_parameters(PyObject *);
__PYX_EXTERN_C std::vector<std::vector<double> >  get_fmp_prior_mus(PyObject *);
__PYX_EXTERN_C std::vector<std::vector<double> >  get_fmp_prior_sigmas(PyObject *);
__PYX_EXTERN_C std::vector<std::vector<std::string> >  get_fmp_prior_models(PyObject *);
__PYX_EXTERN_C std::vector<std::vector<double> >  get_d_fmp(PyObject *);
__PYX_EXTERN_C std::vector<int>  get_rest_index(PyObject *, std::vector<int> );
__PYX_EXTERN_C std::vector<int>  get_para_indices(PyObject *, std::vector<int> );
__PYX_EXTERN_C void build_exp_ref(PyObject *, int);
__PYX_EXTERN_C PyObject *build_gaussian_ref(PyObject *, int, bool);
__PYX_EXTERN_C void build_exp_ref_pf(PyObject *, int);
__PYX_EXTERN_C void build_gaussian_ref_pf(PyObject *, int);
__PYX_EXTERN_C std::vector<std::vector<double> >  build_reference_potentials(PyObject *);
__PYX_EXTERN_C PyObject *Trajectory(PyObject *, int);

#endif /* !__PYX_HAVE_API__PosteriorSampler */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initPosteriorSampler(void);
#else
PyMODINIT_FUNC PyInit_PosteriorSampler(void);
#endif

#endif /* !__PYX_HAVE__PosteriorSampler */
